apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: womenswear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE
              value: "http://api.womenswear.local/order"
            - name: NEXT_PUBLIC_PRODUCT_BASE
              value: "http://api.womenswear.local/product"
            - name: NEXT_PUBLIC_USER_BASE
              value: "http://api.womenswear.local/user"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: womenswear
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
