apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: womenswear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ORDER_DB_URL
              valueFrom:
                secretKeyRef:
                  name: womenswear-secrets
                  key: ORDER_DB_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: womenswear-secrets
                  key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: womenswear-secrets
                  key: JWT_SECRET
            - name: JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: womenswear-config
                  key: JWT_ALG
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: womenswear-config
                  key: USER_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: womenswear-config
                  key: PRODUCT_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: womenswear-config
                  key: PAYMENT_SERVICE_URL
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: womenswear-config
                  key: RABBITMQ_EXCHANGE
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: womenswear-config
                  key: RABBITMQ_QUEUE
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: womenswear
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
