apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db
  namespace: womenswear
spec:
  serviceName: order-db
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "order_service"
            - name: POSTGRES_PASSWORD
              value: "order_service"
            - name: POSTGRES_DB
              value: "order_service"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: womenswear
spec:
  selector:
    app: order-db
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
