apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: womenswear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: womenswear-secrets
                  key: MONGO_URL
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: womenswear-secrets
                  key: MONGO_DB
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: womenswear
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
