apiVersion: v1
kind: Secret
metadata:
  name: womenswear-secrets
  namespace: womenswear
type: Opaque
stringData:
  JWT_SECRET: "change_me_super_secret"
  USER_DB_URL: "postgresql+psycopg://user_service:user_service@user-db:5432/user_service"
  ORDER_DB_URL: "postgresql+psycopg://order_service:order_service@order-db:5432/order_service"
  PAYMENT_DB_URL: "postgresql+psycopg://payment_service:payment_service@payment-db:5432/payment_service"
  MONGO_URL: "mongodb://product-mongo:27017"
  MONGO_DB: "product_service"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
